name:                FoundationMUD
version:             0.1.0.0
github:              "MrLenin/FoundationMUD"
license:             BSD3
author:              "MrLenin"
maintainer:          "ibutsu@gmail.com"
copyright:           "2020 MrLenin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/FoundationMUD#readme>

dependencies:
- base >= 4.7 && < 5
- telnet >= 0.1.0.0

library:
  source-dirs: src

executables:
  FoundationMUD-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - FoundationMUD

tests:
  FoundationMUD-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - FoundationMUD
