name:                telnet
version:             0.1.0.0
github:              "MrLenin/telnet"
license:             BSD3
author:              "MrLenin"
maintainer:          "ibutsu@gmail.com"
copyright:           "2020 MrLenin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/MrLenin/telnet#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.10.8.1
- text >= 1.2.4.0
- mtl >= 2.2.2
- strings >= 1.1

library:
  source-dirs: src

executables:
  telnet-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - telnet

tests:
  telnet-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - telnet
